# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milioner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 598)
        MainWindow.setMinimumSize(QtCore.QSize(800, 598))
        MainWindow.setMaximumSize(QtCore.QSize(800, 598))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/pngegg (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #0b0c2f,   /* очень темный синий */\n"
"        stop:0.4 #1a1a4d, /* глубокий сумеречный синий */\n"
"        stop:0.7 #2a2a6f, /* приглушенный синий с фиолетовым оттенком */\n"
"        stop:1 #3a3a8f  /* мягкий фиолетово-синий */\n"
"    );\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 130, 801, 471))
        self.label.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("R.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 440, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 90); /* чуть менее прозрачный при наведении */\n"
"    border-color: rgba(255, 255, 255, 150);    /* обводка ярче при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 40); /* ещё более прозрачный при нажатии */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 440, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 90); /* чуть менее прозрачный при наведении */\n"
"    border-color: rgba(255, 255, 255, 150);    /* обводка ярче при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 40); /* ещё более прозрачный при нажатии */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 440, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 90); /* чуть менее прозрачный при наведении */\n"
"    border-color: rgba(255, 255, 255, 150);    /* обводка ярче при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 40); /* ещё более прозрачный при нажатии */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 440, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 90); /* чуть менее прозрачный при наведении */\n"
"    border-color: rgba(255, 255, 255, 150);    /* обводка ярче при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 40); /* ещё более прозрачный при нажатии */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 530, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(" background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"padding: 6px 12px;\n"
"\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 781, 191))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(" background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"padding: 6px 12px;\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 0, 201, 201))
        self.label_4.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("pngegg (2).png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 530, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(" background-color: rgba(255, 255, 255, 60); /* белый с прозрачностью 60/255 */\n"
"    color: #ffffff;                             /* белый текст */\n"
"    border: 2px solid rgba(255, 255, 255, 100); /* обводка с небольшой прозрачностью */\n"
"    border-radius: 12px;                        /* закругление углов */\n"
"padding: 6px 12px;\n"
"\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "1pruf"))
        self.pushButton_2.setText(_translate("MainWindow", "2pruf"))
        self.pushButton_3.setText(_translate("MainWindow", "3pruf"))
        self.pushButton_4.setText(_translate("MainWindow", "4pruf"))
        self.label_2.setText(_translate("MainWindow", "Money:"))
        self.label_3.setText(_translate("MainWindow", "Вопрос:"))
        self.label_5.setText(_translate("MainWindow", "Сложность:"))
